config/routes.rb
Rails.application.routes.draw do
    #require "admin_constraint"
    require 'sidekiq/web'

    #constraints lambda {|request| AuthConstraint.admin?(request) } do
    mount Sidekiq::Web => '/admin/sidekiq'


  devise_for :users, controllers: {
    registrations: 'registrations',
    passwords: 'users/passwords'
  }  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users do
    resources :parcels
  end

  resources :parcels do
    member do
      get 'update_status' => 'parcels#update_status', as: 'update_parcel_status'
    end
  end

  namespace :api do
    resources :parcels
    resources :users
  end

  root to: 'parcels#index'end

app/models/parcel.rb
class Parcel
    include Mongoid::Document
    include Mongoid::Timestamps

    field :user_id, type: String
    field :tracking_code, type: String
    field :origin_address_id, type: String
    field :destination_address_id, type: String
    field :receiver_name, type: String
    field :receiver_phone, type: String
    field :receiver_email, type: String
    field :created_at, type: DateTime
    field :updated_at, type: DateTime
    field :status, type: String

    has_many :track_events

    def origin_address
        address = Address.where(id: origin_address_id).first
        "#{address.street} #{address.ext_number} #{address.int_number}, #{address.city}, #{address.country}"
    end

    def destination_address
        address = Address.find_by(id: destination_address_id)
        "#{address.street} #{address.ext_number} #{address.int_number}, #{address.city}, #{address.country}"
    end

    def detect_location(position_index) # position_index in TrackEvent::EVENTS_LIST
        if position_index < 3
            address = Address.find_by(id: origin_address_id)           
        else
            address = Address.find_by(id: destination_address_id)
        end
        "#{address.city}, #{address.country}"
    end

    def current_status
        latest_update = track_events.order(updated_at: :desc).first
        if latest_update
            position_index = TrackEvent::EVENTS_LIST.index(latest_update.description)
            new_event = TrackEvent::EVENTS_LIST[position_index + 1]
            return {
                position_index: position_index,
                new_event: new_event
            }
        else
            return {
                position_index: 0,
                new_event: TrackEvent::EVENTS_LIST.first
            }
        end
    end

    def update_track_history
        latest_update = track_events.order(updated_at: :desc).first
        if latest_update
            position_index = TrackEvent::EVENTS_LIST.index(latest_update.description)
            new_event = TrackEvent::EVENTS_LIST[position_index + 1]
            track_events.create(
                location: detect_location(position_index + 1),
                description: new_event
            )

            # Check if package has arrived to the final update
            if position_index + 1 == TrackEvent::EVENTS_LIST.length - 1
                update status: 'delivered'
            end
        else
            track_events.create(
                location: detect_location(0),
                description: TrackEvent::EVENTS_LIST.first
            )
        end
    end
end

app/controllers/api/parcels_controller.rb
#These are the endpoints for the parcels data in the API
class Api::ParcelsController < Api::BaseController

    def create
        origin_address = Address.create(origin_address_params)
        destination_address = Address.create(destination_address_params)
        parcel = Parcel.new(parcel_params.merge(origin_address_id: origin_address.id, destination_address_id: destination_address.id))
    
        if parcel.save
            render json: {result: 'Parcel was created'}, status: :ok
        else
            render json: {error_messages: parcel.errors.messages.values.join(', ')}, status: :unprocessable_entity
        end
    end

    protected

    def parcel_params
        params.require(:parcel).permit(:tracking_code, :receiver_name, :receiver_phone, :receiver_email)
    end

    def origin_address_params
        params.require(:origin_address).permit(:street, :ext_number, :int_number, :city, :country, :zip_code)
    end
    
    def destination_address_params
        params.require(:destination_address).permit(:street, :ext_number, :int_number, :city, :country, :zip_code)
    end

end

app/controllers/parcels_controller.rb
class ParcelsController < ApplicationController
    def index
        @parcels = Parcel.all
    end

    def show
        @parcel = Parcel.find_by id: params[:id]
        @origin_address = Address.find_by id: @parcel.origin_address_id
        @destination_address = Address.find_by id: @parcel.destination_address_id
    end

    def update_status
        @parcel = Parcel.find_by id: params[:id]
        if @parcel.update_track_history
            message = 'Track history updated'
        else
            message = 'There was an error'
        end
        redirect_to parcel_path, notice: message
    end
end

app/views/parcels/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="col-md-12">
        <h4 class="float-left">Parcels</h4>
    </li>
  </ol>
</nav>



<hr>

<table class="table">
<thead>
<tr>
<th>Tracking code</th>
<th>Origin</th>
<th>Destination</th>
<th>Receiver name</th>
<th>Receiver phone</th>
<th>Receiver e-mail</th>
<th>Creation date</th>
</tr>
</thead>
<tbody>
<% @parcels.each do |parcel| %>
    <tr>
    <td><%= link_to parcel.tracking_code, user_parcel_path(current_user.id, parcel.id), class: 'btn btn-warning' %></td>
    <td><%= parcel.origin_address %></td>
    <td><%= parcel.destination_address %></td>
    <td><%= parcel.receiver_name %></td>
    <td><%= parcel.receiver_phone %></td>
    <td><%= parcel.receiver_email %></td>
    <td><%= parcel.created_at %></td>
    </tr>
<% end %>
</tbody>
</table>

app/views/parcels/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="col-md-12">
        <h4 class="float-left">Parcel - <%= @parcel.tracking_code %></h4>
    </li>
  </ol>
</nav>

<div class="row">
<div class="col-md-12">
<div class="card">
  <div class="card-body">
    <h5 class="card-title">Receiver: <%= @parcel.receiver_name %></h5>
    <hr>
    <div class="row">Phone: <%= @parcel.receiver_phone %></div>
    <div class="row">e-mail: <%= @parcel.receiver_email %></div>
  </div>

</div>
</div>
</div>

<hr>

<div class="row">
  <div class="col-sm-6">
    <div class="card" style="width: 34rem;">
          <div class="card-body">
            <h5 class="card-title">Origin Address</h5>
            <hr>
            <div>
              <p><strong>Street:</strong>&nbsp;<%= @origin_address.street %></p>
              <p><strong>External number:</strong>&nbsp;<%= @origin_address.ext_number %></p>
              <p><strong>Appartment:</strong>&nbsp;<%= @origin_address.int_number %></p>
              <p><strong>City:</strong>&nbsp;<%= @origin_address.city %></p>
              <p><strong>Country:</strong>&nbsp;<%= @origin_address.country %></p>
              <p><strong>ZIP code:</strong>&nbsp;<%= @origin_address.zip_code %></p>
            </div>
          </div>

    </div>
  </div>
  <div class="col-sm-6">
    <div class="card" style="width: 34rem;">
          <div class="card-body">
            <h5 class="card-title">Destination Address</h5>
            <hr>
            <div>
              <p><strong>Street:</strong>&nbsp;<%= @destination_address.street %></p>
              <p><strong>External number:</strong>&nbsp;<%= @destination_address.ext_number %></p>
              <p><strong>Appartment:</strong>&nbsp;<%= @destination_address.int_number %></p>
              <p><strong>City:</strong>&nbsp;<%= @destination_address.city %></p>
              <p><strong>Country:</strong>&nbsp;<%= @destination_address.country %></p>
              <p><strong>ZIP code:</strong>&nbsp;<%= @destination_address.zip_code %></p>
            </div>
          </div>
    </div>
  </div>

</div>
<hr>
<h3>Tracking History</h3>
<table class="table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Location</td>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
        <tr>
            <td><%= @parcel.created_at %></td>
            <td>&nbsp;</td>
            <td>Added into the system</td>
        </tr>
        <% @parcel.track_events.each do |event| %>
            <tr>
                <td><%= event.created_at %></td>
                <td><%= event.location %></td>
                <td><%= event.description %></td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Update status', update_parcel_status_parcel_path(@parcel.id), class: 'btn btn-primary' %>
<span>Next: <%= @parcel.current_status[:new_event] %></span><br /><br />
<%= link_to 'Back', root_path, class: 'btn btn-primary' %>